version: 0.2

phases:
  install:
    runtime-versions:
        docker: 18
        python: 3.7
    commands:
      - make setup-codebuild
  pre_build:
    commands:
      - export COMMIT_SHA=${CODEBUILD_RESOLVED_SOURCE_VERSION} # Commit SHA that triggered this build
      - export DEPLOY_ENV=$(echo ${CODEBUILD_WEBHOOK_TRIGGER} | sed -e 's/branch\/master/dev/' | sed -e 's/branch\/production/prod/')
      - if [ -z "${DEPLOY_ENV}" ]; then export DEPLOY_ENV="dev"; fi
      - echo "Running for ${COMMIT_SHA} in ${DEPLOY_ENV}"
      - make login CLUSTER_NAME=${CLUSTER_NAME}
  build:
    commands:
      - make build COMMIT_SHA=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - make push DOCKER_DEST=${DOCKER_REPO}:${CODEBUILD_RESOLVED_SOURCE_VERSION}
  post_build:
    commands:
      - make release STAGE=${DEPLOY_ENV}
