DASHBOARD_CSP = {
    "default-src": ["'self'"],
    "script-src": [
        "'self'",
        "https://ajax.googleapis.com",
        "https://fonts.googleapis.com",
        "https://*.googletagmanager.com",
        "https://tagmanager.google.com",
        "https://*.google-analytics.com",
        "https://cdn.sso.mozilla.com",
        "https://cdn.sso.allizom.org",
    ],
    "style-src": [
        "'self'",
        "https://ajax.googleapis.com",
        "https://fonts.googleapis.com",
        "https://cdn.sso.mozilla.com",
        "https://cdn.sso.allizom.org",
    ],
    "img-src": [
        "'self'",
        "https://*.mozillians.org",
        "https://cdn.sso.mozilla.com",
        "https://cdn.sso.allizom.org",
        "https://*.google-analytics.com",
        "https://*.gravatar.com",
        "https://i0.wp.com/",
        "https://i1.wp.com",
    ],
    "font-src": [
        "'self'",
        "https://fonts.googleapis.com",
        "https://fonts.gstatic.com",
        "https://cdn.sso.mozilla.com",
        "https://cdn.sso.allizom.org",
    ],
}
