graph TD

dns((route53 zones)) --> ingress_controller

ingress_controller[kubernetes_ingress_controller_with_ssl] -->

container[sso-dashboard-container] -- fetch assets and access file --> cdn[cdn.sso.mozilla.com]

container[sso-dashboard-container] -- fetch secrets --> credstash --> client_id,client_secret,etc

cdn[cdn.sso.mozilla.com] -->
access_file(apps.yml)
cdn[cdn.sso.mozilla.com] --> images(img, css, js)
