graph TD

%% Define entites
user((fa:fa-user SSO Dashboard User))
idp([Auth0])
gcpLoadBalancer([GCP Load Balancer])
subgraph cloudrun [GCP Cloud Run Environment]
    gcpCloudRunContainer1[[Container 1]]
    gcpCloudRunContainer2[[Container 2]]
    gcpCloudRunContainer3[[Container 3]]
end
subgraph CloudFrontCDN [AWS]
    awsCDN([cdn.sso.mozilla.com])
    appImages(img, css, js)
    appAppsYaml(apps.yml)
end

gcpSecretsManager[(fa:fa-database GCP Secrets Manager)]
appSecrets(Application Secrets)

%% Define Flows
user <--> idp

user -->
gcpLoadBalancer -->
cloudrun -->
CloudFrontCDN

awsCDN --> appImages
awsCDN --> appAppsYaml

cloudrun -->
gcpSecretsManager -->
appSecrets
